# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 737)
        MainWindow.setMinimumSize(QtCore.QSize(450, 350))
        self.stylesheet = QtWidgets.QWidget(MainWindow)
        self.stylesheet.setStyleSheet("#stylesheet {\n"
"background-image: url(\':/images/images/background.jpeg\');\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"color: white;\n"
"background-color: rgba(0,0,0,220);\n"
"}\n"
"* {\n"
"font: 8pt \"Inconsolata Expanded\";\n"
"}\n"
"\n"
"\n"
"#loginButton, #signupButton {\n"
"color: #FFF;\n"
"font: 75 8pt \"Inconsolata Expanded\";\n"
"font-weight: 700;\n"
"line-height: 123.9%; /* 19.642px */\n"
"background: transparent;\n"
"border: 1px solid white;\n"
"padding: 5px 15px;\n"
"border-radius: 5px;\n"
"margin-top: 20px;\n"
"}\n"
"\n"
"#helpButton {\n"
"color: #FFF;\n"
"font: 75 8pt \"Inconsolata Expanded\";\n"
"font-weight: 700;\n"
"line-height: 123.9%; /* 19.642px */\n"
"background: transparent;\n"
"border: none;\n"
"padding: 5px 15px;\n"
"border-radius: 5px;\n"
"margin-top: 20px;\n"
"}\n"
"\n"
"#uploadDocumentFrame {\n"
"border-radius: 22.338px;\n"
"border: 1.862px dashed #FFF;\n"
"background: rgba(255, 255, 255, 0.08);\n"
"}\n"
"#cloudIconButton {\n"
"background: transparent;\n"
"}\n"
"#dragAndDropLabel {\n"
"color: #FFF;\n"
"font: 8pt \"Palatino Linotype\";\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"line-height: normal;\n"
"}\n"
"#selectFileLabel {\n"
"color: rgba(255, 255, 255, 0.30);\n"
"text-align: center;\n"
"font: 8pt \"Palatino Linotype\";\n"
"font-size: 22.338px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"}\n"
"\n"
"#downloadButtonInformation {\n"
"border-radius: 6px;\n"
"border: 1px solid #FFF;\n"
"padding: 10px 40px;\n"
"}\n"
"#downloadButton {\n"
"border-radius: 2px;\n"
"background: #F6751E;\n"
"color: black;\n"
"padding: 7px 25px;\n"
"font: 75 10pt \"Inconsolata Condensed\";\n"
"font-weight: 700;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border-radius: 2px;\n"
"    background-color: rgba(255, 255, 255, 75);\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #F6751E;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.stylesheet.setObjectName("stylesheet")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.stylesheet)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contentFrame = QtWidgets.QFrame(self.stylesheet)
        self.contentFrame.setStyleSheet("#contentFrame {\n"
"background-color: rgba(0, 0, 0, 0.85);\n"
"}")
        self.contentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerFrame = QtWidgets.QFrame(self.contentFrame)
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.headerFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logoButton = QtWidgets.QPushButton(self.frame)
        self.logoButton.setStyleSheet("border: none;\n"
"")
        self.logoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoButton.setIcon(icon)
        self.logoButton.setIconSize(QtCore.QSize(110, 35))
        self.logoButton.setObjectName("logoButton")
        self.verticalLayout_3.addWidget(self.logoButton, 0, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 8pt \"Inknut Antiqua\";\n"
"")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.signupButton = QtWidgets.QPushButton(self.headerFrame)
        self.signupButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.signupButton.setObjectName("signupButton")
        self.horizontalLayout.addWidget(self.signupButton, 0, QtCore.Qt.AlignTop)
        self.loginButton = QtWidgets.QPushButton(self.headerFrame)
        self.loginButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton, 0, QtCore.Qt.AlignTop)
        self.helpButton = QtWidgets.QPushButton(self.headerFrame)
        font = QtGui.QFont()
        font.setFamily("Inconsolata Expanded")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.helpButton.setFont(font)
        self.helpButton.setStyleSheet("")
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.headerFrame)
        self.bodyFrame = QtWidgets.QFrame(self.contentFrame)
        self.bodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bodyFrame.setObjectName("bodyFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bodyFrame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.bodyFrame)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setStyleSheet("* {\n"
"color: white;\n"
"background: transparent;\n"
"}\n"
"#downloadButton {\n"
"border-radius: 6px;\n"
"background: #F6751E;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.uploadDocumentFrame = DroppableFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadDocumentFrame.sizePolicy().hasHeightForWidth())
        self.uploadDocumentFrame.setSizePolicy(sizePolicy)
        self.uploadDocumentFrame.setMinimumSize(QtCore.QSize(300, 180))
        self.uploadDocumentFrame.setStyleSheet("#uploadDocumentFrame {\n"
"background-color: rgba(255, 255, 255, 75);\n"
"}")
        self.uploadDocumentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uploadDocumentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.uploadDocumentFrame.setObjectName("uploadDocumentFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.uploadDocumentFrame)
        self.verticalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cloudIconButton = QtWidgets.QPushButton(self.uploadDocumentFrame)
        self.cloudIconButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/upload-cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cloudIconButton.setIcon(icon1)
        self.cloudIconButton.setIconSize(QtCore.QSize(30, 30))
        self.cloudIconButton.setObjectName("cloudIconButton")
        self.verticalLayout_4.addWidget(self.cloudIconButton, 0, QtCore.Qt.AlignHCenter)
        self.dragAndDropLabel = QtWidgets.QLabel(self.uploadDocumentFrame)
        self.dragAndDropLabel.setObjectName("dragAndDropLabel")
        self.verticalLayout_4.addWidget(self.dragAndDropLabel, 0, QtCore.Qt.AlignHCenter)
        self.selectFileLabel = QtWidgets.QLabel(self.uploadDocumentFrame)
        self.selectFileLabel.setObjectName("selectFileLabel")
        self.verticalLayout_4.addWidget(self.selectFileLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_6.addWidget(self.uploadDocumentFrame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 20))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border-radius: 2px;\n"
"    background-color: rgba(255, 255, 255, 75);\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #F6751E;\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_10.addWidget(self.progressBar)
        self.verticalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.downloadFrame = QtWidgets.QFrame(self.page_2)
        self.downloadFrame.setMinimumSize(QtCore.QSize(350, 0))
        self.downloadFrame.setStyleSheet("#downloadFrame {\n"
"border-radius: 6px;\n"
"background: rgba(0, 0, 0, 0.78);}")
        self.downloadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadFrame.setObjectName("downloadFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.downloadFrame)
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.downloadFrame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2, 0, QtCore.Qt.AlignBottom)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(90, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(10000, 1))
        self.frame_2.setStyleSheet("background: #FFF;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9.addWidget(self.frame_2)
        self.verticalLayout_8.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.downloadFrame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.downloadButtonInformation = QtWidgets.QPushButton(self.downloadFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/file-type-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadButtonInformation.setIcon(icon2)
        self.downloadButtonInformation.setObjectName("downloadButtonInformation")
        self.verticalLayout_8.addWidget(self.downloadButtonInformation, 0, QtCore.Qt.AlignHCenter)
        self.downloadButton = QtWidgets.QPushButton(self.downloadFrame)
        self.downloadButton.setStyleSheet("color: black")
        self.downloadButton.setObjectName("downloadButton")
        self.verticalLayout_8.addWidget(self.downloadButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.verticalLayout_8.setStretch(1, 1)
        self.verticalLayout_8.setStretch(2, 2)
        self.verticalLayout_8.setStretch(3, 2)
        self.verticalLayout_8.setStretch(4, 1)
        self.verticalLayout_7.addWidget(self.downloadFrame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.bodyFrame)
        self.footerFrame = QtWidgets.QFrame(self.contentFrame)
        self.footerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footerFrame.setObjectName("footerFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footerFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.footerFrame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.footerFrame)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.verticalLayout.addWidget(self.contentFrame)
        MainWindow.setCentralWidget(self.stylesheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Welcome to </span><span style=\" color:#f6751e;\">PHOENIX</span><span style=\" color:#ffffff;\"> Resourcing Group</span></p></body></html>"))
        self.signupButton.setText(_translate("MainWindow", "Signup"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.helpButton.setText(_translate("MainWindow", "Help"))
        self.dragAndDropLabel.setText(_translate("MainWindow", "Drag & Drop"))
        self.selectFileLabel.setText(_translate("MainWindow", "or select files from device"))
        self.label_2.setText(_translate("MainWindow", "You’re File is here"))
        self.label_3.setText(_translate("MainWindow", "Click to Download"))
        self.downloadButtonInformation.setText(_translate("MainWindow", "Document.docx"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
from droppableframe import DroppableFrame
import resources_rc
